name: test

on:
  workflow_call:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
      - 'example/**'
      - '**/*.md'

jobs:
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: test
        run: pnpm run test
      # - name: ✅ Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3